# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20161021_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_code',
        ),
    ]
