# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20161014_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
