# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productmanufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'brand',
                'ordering': ('brand',),
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.RemoveField(
            model_name='productmanufacturer',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductManufacturer',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.ProductBrand'),
            preserve_default=False,
        ),
    ]
